language: java
jdk: openjdk11
before_install:
  - git clone --branch 2.5.x https://github.com/openhab/openhab-addons
  - cd openhab-addons
  - git remote add pfink https://${GH_TOKEN}@github.com/pfink/openhab-addons
  - git fetch pfink ${TRAVIS_BRANCH} || true
  - git branch ${TRAVIS_BRANCH} && git checkout ${TRAVIS_BRANCH} && git pull || true
  - cd ..
  - mkdir -p openhab-addons/bundles/org.openhab.binding.flicbutton
  - rm -rf .git
  - shopt -s extglob dotglob
  - mv !(openhab-addons) openhab-addons/bundles/org.openhab.binding.flicbutton
  - cd openhab-addons/bundles/org.openhab.binding.flicbutton
  - rm -rf .travis.yml
  - git add .
  - git commit -a -m "${TRAVIS_COMMIT_MESSAGE}"  
  - git push pfink ${TRAVIS_BRANCH}
  
